use mongodb::bson::oid::ObjectId;
use rocket::{http::Status, serde::json::Json, State};
use crate::{
    models::Transaction,
    repository::MongoRepo,
};

#[post("/transactions", data = "<new_transaction>")]
pub async fn create_transaction(
    db: &State<MongoRepo>,
    new_transaction: Json<Transaction>,
) -> Result<Json<Transaction>, Status> {
    let mut data = new_transaction.into_inner();
    data.id = None; // Ensure ID is generated by MongoDB
    
    let result = db.create_transaction(data).await;
    match result {
        Ok(_) => Ok(Json(db.get_all_transactions().await.map_err(|_| Status::InternalServerError)?.into_iter().last().unwrap())), // This is a bit hacky, but works for now as create_transaction doesn't return the ID easily without modifying it to return InsertOneResult
        Err(_) => Err(Status::InternalServerError),
    }
}

#[get("/transactions")]
pub async fn get_all_transactions(db: &State<MongoRepo>) -> Result<Json<Vec<Transaction>>, Status> {
    let transactions = db.get_all_transactions().await;
    match transactions {
        Ok(transactions) => Ok(Json(transactions)),
        Err(_) => Err(Status::InternalServerError),
    }
}

#[get("/transactions/<id>")]
pub async fn get_transaction_by_id(
    db: &State<MongoRepo>,
    id: String,
) -> Result<Json<Transaction>, Status> {
    let object_id = ObjectId::parse_str(&id).map_err(|_| Status::BadRequest)?;
    let transaction = db.get_transaction_by_id(object_id).await;
    match transaction {
        Ok(Some(t)) => Ok(Json(t)),
        Ok(None) => Err(Status::NotFound),
        Err(_) => Err(Status::InternalServerError),
    }
}
